#!/bin/bash

## Change this ##

OUTPUT="sprite.gif"
OUTPUT_CSS="sprite.css"
ICON_SIZE="14"

## Should not change ##

TMP_DIR="._faviconsprite_tmp"

## Absolutly not change ##
###############################################################################

COLS=0
ROWS=0

function beautify() {
  echo $1 | sed 's/\./_/g'
}

function download_favicon() {
  local domain="$1"
  local src="http://${domain}/favicon.ico"
  local dst="$( beautify $domain )"
  wget --quiet "${src}" -O "${dst}.ico"
  convert "${dst}.ico" -resize ${ICON_SIZE}x${ICON_SIZE} "${dst}.png"
  rm "${dst}.ico"
  echo "${dst}.png"
}

function read_answer() {
  local answer;
  read answer;
  echo $answer;
}

function check_if_directory_exists() {
  if [ -e "${TMP_DIR}" ]; then {
    echo "Error: $TMP_DIR directory exists. Rewrite? y/N"
    if [ "$( read_answer )" == "y" ]; then {
      rm -r "${TMP_DIR}"   
    } else {
      echo "Aborting"
      exit
    } fi
  } fi
}

function generate_css() {
  k=0
  c=0
  r=0
  for i in $@; do {
    let "x=c*ICON_SIZE"
    let "y=r*ICON_SIZE"
    position="${x}px ${y}px"
    echo ".icon-$( beautify $i ) { background-position: $position; }"
    let "k++"
    let "c++"
    if [ $c -gt $ROWS ]; then c=0; let "r++"; fi
  } done
}

function generate_sprite() {
  echo "Downloading"
  cd "${TMP_DIR}"
  icons=""
  for i in $@; do {
    icon=$( download_favicon "$i" )
    icons="${icons} $icon"
  } done
  echo
  echo "Generating sprite"
  montage -background transparent -geometry +0+0 $icons "${OUTPUT}"
  calculate_row_col
  echo "Generating css"
  generate_css $@ > "${OUTPUT_CSS}"
}

function calculate_row_col() {
  local sprite_size=$( identify "${OUTPUT}" | awk '{ print $3 }' )
  local sprite_width=$( echo $sprite_size | sed 's/x.*//' )
  local sprite_height=$( echo $sprite_size | sed 's/.*x//' )
  let "COLS=sprite_width/${ICON_SIZE}"
  let "ROWS=sprite_height/${ICON_SIZE}"
}

#check_if_directory_exists

#mkdir "${TMP_DIR}"

( generate_sprite $@ )
